"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import {
  Scale,
  ArrowRight,
  Play,
  Star,
  BookOpen,
  Shield,
  MessageSquare,
  Award,
} from "lucide-react";

const benefits = [
  {
    icon: BookOpen,
    title: "Legal Education Content",
    description:
      "Explain complex legal concepts in accessible, engaging video format. Position yourself as the trusted authority in your practice area.",
  },
  {
    icon: Shield,
    title: "Know Your Rights Series",
    description:
      "Automated weekly videos covering common legal questions. Generated by Kling 2.6 with your authentic voice and delivery style.",
  },
  {
    icon: MessageSquare,
    title: "Client Testimonial Videos",
    description:
      "Transform written reviews into powerful video testimonials using Seedance 2.0, building social proof that converts.",
  },
  {
    icon: Award,
    title: "Thought Leadership",
    description:
      "Commentary on legal news, case studies, and industry updates. Establish yourself as the go-to expert without spending hours filming.",
  },
];

const stats = [
  { value: "5x", label: "More consultations booked" },
  { value: "78%", label: "Increase in website traffic" },
  { value: "4x", label: "Social media engagement" },
  { value: "12hrs", label: "Saved per week" },
];

export default function AttorneysPage() {
  return (
    <>
      {/* Hero */}
      <section className="relative min-h-[85vh] flex items-center justify-center overflow-hidden pt-20">
        <div className="absolute inset-0 mesh-gradient" />
        <div className="hero-glow bg-purple-500 top-1/4 -left-40" />
        <div className="hero-glow bg-pink-600 bottom-1/4 -right-40" />

        <div className="container-max relative z-10 px-4 sm:px-6 lg:px-8 py-20 md:py-32">
          <div className="max-w-4xl mx-auto text-center">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-purple-500/10 border border-purple-500/20 mb-8"
            >
              <Scale className="w-4 h-4 text-purple-400" />
              <span className="text-sm font-medium text-purple-300">
                For Legal Professionals
              </span>
            </motion.div>

            <motion.h1
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="text-5xl sm:text-6xl md:text-7xl font-bold tracking-tight leading-[1.05] mb-8"
            >
              Build your legal{" "}
              <span className="gradient-text">reputation</span> online
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              className="text-lg sm:text-xl text-gray-400 max-w-2xl mx-auto mb-12"
            >
              AI-powered video content that educates, builds trust, and converts
              viewers into clients. Powered by Kling 2.6 and Seedance 2.0.
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className="flex flex-col sm:flex-row items-center justify-center gap-4"
            >
              <Link href="/signup" className="btn-primary gap-2 text-lg">
                Start your free trial
                <ArrowRight className="w-5 h-5" />
              </Link>
              <Link href="/demo" className="btn-secondary gap-2 text-lg">
                <Play className="w-5 h-5" />
                Watch demo
              </Link>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Stats */}
      <section className="section-padding">
        <div className="container-max">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-6">
            {stats.map((stat, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="glass-card p-6 text-center"
              >
                <div className="text-3xl sm:text-4xl font-bold gradient-text mb-2">
                  {stat.value}
                </div>
                <div className="text-sm text-gray-400">{stat.label}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Benefits */}
      <section className="section-padding">
        <div className="container-max">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="text-4xl sm:text-5xl font-bold tracking-tight mb-6"
            >
              Content that builds{" "}
              <span className="gradient-text">trust</span>
            </motion.h2>
            <motion.p
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.1 }}
              className="text-lg text-gray-400"
            >
              Legal marketing that educates and converts, without compromising
              your professional standards.
            </motion.p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {benefits.map((benefit, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="glass-card p-8 hover:border-white/10 transition-all"
              >
                <div className="w-12 h-12 rounded-xl bg-purple-500/10 flex items-center justify-center mb-5">
                  <benefit.icon className="w-6 h-6 text-purple-400" />
                </div>
                <h3 className="text-xl font-bold mb-3">{benefit.title}</h3>
                <p className="text-gray-400 leading-relaxed">
                  {benefit.description}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="section-padding">
        <div className="container-max">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="glass-card p-12 md:p-16 text-center relative overflow-hidden"
          >
            <div className="absolute top-0 left-1/4 w-96 h-96 bg-purple-500 rounded-full filter blur-[150px] opacity-10" />
            <h2 className="text-4xl sm:text-5xl font-bold tracking-tight mb-6 relative z-10">
              Ready to grow your{" "}
              <span className="gradient-text">practice?</span>
            </h2>
            <p className="text-lg text-gray-400 max-w-2xl mx-auto mb-8 relative z-10">
              Join attorneys across the country who are using AI video content to
              attract more clients and build their reputation.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 relative z-10">
              <Link href="/signup" className="btn-primary gap-2">
                Start your free trial <ArrowRight className="w-5 h-5" />
              </Link>
              <Link href="/demo" className="btn-secondary gap-2">
                Book a demo
              </Link>
            </div>
          </motion.div>
        </div>
      </section>
    </>
  );
}
